rishat_ta/item_app/urls.py
from django.urls import path

from . import views

app_name = 'item_app'

urlpatterns = [
    # Оплата одного предмета
    path('item/<int:item_id>/', views.item, name='item'),
    path(
        'buy/<id>/',
        views.item_checkout_session,
        name='item_checkout_session'
    ),
    # Оплата заказа
    path('order/<int:order_id>/', views.order, name='order'),
    path(
        'buy-order/<id>/',
        views.order_checkout_session,
        name='order_checkout_session'
    ),
    # Странички успешной и неуспешной оплаты
    path('success/', views.PaymentSuccessView.as_view(), name='success'),
    path('failed/', views.PaymentFailedView.as_view(), name='failed'),
]

rishat_ta/rishat_ta/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('item_app.urls', namespace='item_app')),
    path('admin/', admin.site.urls),
]

rishat_ta/item_app/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Item(models.Model):
    name = models.CharField(
        'Наименование предмета',
        max_length=200
    )
    description = models.TextField(
        'Описание'
    )
    price = models.DecimalField(
        'Цена',
        max_digits=8,
        decimal_places=2
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Предмет'
        verbose_name_plural = 'Предметы'


class Tax(models.Model):
    tax_name = models.CharField(
        'Тип налога',
        max_length=50
    )
    tax_amount = models.DecimalField(
        'Налог',
        max_digits=5,
        decimal_places=2,
        validators=[MinValueValidator(0), MaxValueValidator(100)]
    )
    stripe_tax_rate_id = models.SlugField(
        'Stripe_tax_rate_ID',
        max_length=200,
        unique=True,
        blank=True,
        null=True,
    )

    def __str__(self):
        return f'{self.tax_name}: {self.tax_amount} %'

    class Meta:
        verbose_name = 'Налог'
        verbose_name_plural = 'Налоги'


class Discount(models.Model):
    discount_name = models.CharField(
        'Тип скидки',
        max_length=50
    )
    discount_amount = models.DecimalField(
        'Скидка',
        max_digits=5,
        decimal_places=2,
        validators=[MinValueValidator(0), MaxValueValidator(100)]
    )

    def __str__(self):
        return f'{self.discount_name}: {self.discount_amount} %'

    class Meta:
        verbose_name = 'Скидка'
        verbose_name_plural = 'Скидки'


class Order(models.Model):
    item = models.ManyToManyField(
        Item,
        through='Order_items',
        verbose_name='Наименование предмета'
    )
    discount_amount = models.ForeignKey(
        Discount,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='discounts',
        verbose_name='Скидки'

    )
    tax_amount = models.ForeignKey(
        Tax,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='taxes',
        verbose_name='Налог'
    )

    def __str__(self):
        return f'Заказ №{self.pk}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class Order_items(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name='orders',
        verbose_name='Заказ'
    )
    item = models.ForeignKey(
        Item,
        on_delete=models.CASCADE,
        related_name='items',
        verbose_name='Предметы'
    )
    item_amount = models.IntegerField(
        'Количество предметов'
    )

    def __str__(self):
        return f'{self.order} - {self.item}'

    class Meta:
        verbose_name = 'Предметы в заказе'
        verbose_name_plural = 'Предметы в заказах'

rishat_ta/item_app/views.py
import stripe
from django.conf import settings
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from .models import Item, Order, Order_items, Tax


def item(request, item_id):
    """Рендер страницы оплаты одного предмета."""
    item = get_object_or_404(Item, pk=item_id)

    return render(
        request,
        'item_app/item.html',
        {
            'item': item,
            'stripe_publishable_key': settings.STRIPE_PUBLISHABLE_KEY
        }
    )


@csrf_exempt
def item_checkout_session(request, id):
    """Stripe-сессия оплаты одного предмета."""
    item = get_object_or_404(Item, pk=id)
    stripe.api_key = settings.STRIPE_SECRET_KEY

    checkout_session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=[
            {
                'price_data': {
                    'currency': 'usd',
                    'product_data': {'name': item.name},
                    'unit_amount': int(item.price * 100),
                },
                'quantity': 1,
            }
        ],
        mode='payment',
        success_url='http://localhost/success/',
        cancel_url='http://localhost/failed/',
    )

    return JsonResponse({'sessionId': checkout_session.id})


def order(request, order_id):
    """Рендер страницы оплаты заказа."""
    order = get_object_or_404(Order, pk=order_id)
    items = Order_items.objects.filter(
        order=order).select_related('order', 'item')
    price_sum = sum([item.item_amount * item.item.price for item in items])

    discount_total, tax_total = 0, 0
    if order.discount_amount:
        discount_total = (
            round((price_sum * order.discount_amount.discount_amount / 100), 2)
        )
    if order.tax_amount:
        tax_total = (
            round(
                ((price_sum - discount_total)
                 * order.tax_amount.tax_amount / 100), 2
            )
        )
    total = round((price_sum - discount_total + tax_total), 2)

    return render(
        request,
        'item_app/order.html',
        {
            'items': items,
            'order': order,
            'price_sum': price_sum,
            'discount_total': discount_total,
            'tax_total': tax_total,
            'total': total,
            'stripe_publishable_key': settings.STRIPE_PUBLISHABLE_KEY
        }
    )


def coupon_get_or_create(order):
    """Получение или создание stripe-купона для применения скидки."""
    coupon = {}
    if order.discount_amount:
        try:
            stripe.Coupon.create(
                id=order.discount_amount.pk,
                percent_off=order.discount_amount.discount_amount,
                duration='forever'
            )
        except Exception:
            pass
        coupon = {'coupon': order.discount_amount.pk, }
    return coupon


def tax_get_or_create(order):
    """Получение или создание stripe-налоговой ставки для оплаты налога."""
    tax_rate_id = []
    if order.tax_amount and not order.tax_amount.stripe_tax_rate_id:
        tax_rate = stripe.TaxRate.create(
            display_name=order.tax_amount.tax_name,
            inclusive=False,
            percentage=order.tax_amount.tax_amount
        )
        tax_rate_id = [tax_rate['id']]
        Tax.objects.filter(pk=order.tax_amount.pk).update(
            stripe_tax_rate_id=tax_rate['id'])
    if order.tax_amount and order.tax_amount.stripe_tax_rate_id:
        tax_rate_id = [order.tax_amount.stripe_tax_rate_id]
    return tax_rate_id


@csrf_exempt
def order_checkout_session(request, id):
    """Stripe-сессия для оплаты заказа."""
    order = get_object_or_404(Order, pk=id)
    items = Order_items.objects.filter(
        order=order).select_related('order', 'item')
    price_sum = sum([item.item_amount * item.item.price for item in items])
    stripe.api_key = settings.STRIPE_SECRET_KEY
    checkout_session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=[
            {
                'price_data': {
                    'currency': 'usd',
                    'product_data': {'name': order},
                    'unit_amount': (
                        int(price_sum * 100)
                    ),
                },
                'quantity': 1,
                'tax_rates': tax_get_or_create(order),
            }
        ],
        mode='payment',
        discounts=[coupon_get_or_create(order)],
        success_url='http://localhost/success/',
        cancel_url='http://localhost/failed/',
    )

    return JsonResponse({'sessionId': checkout_session.id})


class PaymentSuccessView(TemplateView):
    template_name = "item_app/success.html"


class PaymentFailedView(TemplateView):
    template_name = "item_app/failed.html"

rishat_ta/templates/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru">          
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" 
      href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" 
      href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" 
      href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <title>
      {% block title %}
      {% endblock %}
    </title>      
  </head>
  <body>
      <main>
        <div class="container py-5">
          {% block content %}
          {% endblock %}
        </div>
      </main>
  </body>
</html>

rishat_ta/templates/item_app/failed.html
{% extends 'base.html' %}

{% block title %}    
  Неудача
{% endblock %}

{% block content %}
<article>
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-body">
          <div class="jumbotron text-center">
            <h3 class="text-danger">Платеж не проведен!</h3>
        </div>
      </div>
    </div>
  </div>
</article>
{% endblock %}

rishat_ta/templates/item_app/item.html
{% extends 'base.html' %}

{% block title %}    
  Оплатить {{ item.name }}
{% endblock %}

{% block content %}
<article>
  <div class="card bg-light mb-3">
    <div class="card-body">
      <h1>{{ item.name }}</h1>
      <p>{{ item.description }}</p>
      <p>Стоимость: {{ item.price }}</p>
      <button id="buy-button">Купить</button>

      <script src="https://js.stripe.com/v3/"></script>
      <script type="text/javascript">
        var stripe = Stripe('{{ stripe_publishable_key }}');
        var buyButton = document.getElementById('buy-button');
        buyButton.addEventListener('click', function() {
          fetch('{% url 'item_app:item_checkout_session' id=item.id %}', {method: 'GET'})
          .then(function (response) {
            return response.json();
          })
          .then(function (session) {
            return stripe.redirectToCheckout({ sessionId: session.sessionId });
          })
        });
      </script>
    </div>
  </div>
</article>
{% endblock %} 

rishat_ta/templates/item_app/order.html
{% extends 'base.html' %}

{% block title %}    
  Оплатить {{ order }}
{% endblock %}

{% block content %}
{% load user_filters %}
<article>
  <div class="card bg-light mb-3">
    <div class="card-body">
      <div class="card-header"><h1>{{ order }}</h1></div>
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Наименование</th>
            <th scope="col">Количество</th>
            <th scope="col">Цена</th>
            <th scope="col">Стоимость</th>
          </tr>
        </thead>
        <tbody>
          {% for item in items %}
          <tr>            
            <td>{{ item.item.name }}</td>
            <td>{{ item.item_amount }}</td>
            <td>{{ item.item.price }} USD</td>
            <td>{{ item.item_amount | multiply:item.item.price }} USD</td>
          </tr>
          {% endfor %}
          <tr>
            <td></td>
            <td></td>
            <th scope="row">Всего:</th>
            <td>{{ price_sum }} USD</td>
          </tr>
          {% if order.discount_amount %}
          <tr>
            <td></td>
            <td></td>
            <th scope="row">Скидка:</th>
            <td>{{ order.discount_amount }}</td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <th scope="row">Сумма скидки:</th>
            <td>{{ discount_total }} USD</td>
          </tr>
          {% endif %}
          {% if order.tax_amount %}
          <tr>
            <td></td>
            <td></td>
            <th scope="row">{{ order.tax_amount.tax_name }}</th>
            <td>{{ order.tax_amount.tax_amount }} %</td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <th scope="row">Сумма налога:</th>
            <td>{{ tax_total }} USD</td>
          </tr>
          {% endif %}
          {% if order.discount_amount or order.tax_amount %}
          <tr>
            <td></td>
            <td></td>
            <th scope="row">Итого:</th>
            <td>{{ total }} USD</td>
          </tr>
          {% endif %}
      </table>
      <button id="buy-button">Купить</button>

      <script src="https://js.stripe.com/v3/"></script>
      <script type="text/javascript">
        var stripe = Stripe('{{ stripe_publishable_key }}');
        var buyButton = document.getElementById('buy-button');
        buyButton.addEventListener('click', function() {
          fetch('{% url 'item_app:order_checkout_session' id=order.id %}', {method: 'GET'})
          .then(function (response) {
            return response.json();
          })
          .then(function (session) {
            return stripe.redirectToCheckout({ sessionId: session.sessionId });
          })
        });
      </script>
    </div>
  </div>
</article>
{% endblock %} 

rishat_ta/templates/item_app/success.html
{% extends 'base.html' %}

{% block title %}    
  Успех
{% endblock %}

{% block content %}
<article>
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-body">
          <div class="jumbotron text-center">
            <h3 class="text-danger">Платеж проведен успешно!</h3>
        </div>
      </div>
    </div>
  </div>
</article>
{% endblock %}